In [7]:
import pandas as pd 
import numpy as np

In [8]:
X_train3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_train3.xlsx")
y_train3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_train3.xlsx")

X_test3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_test3.xlsx")
y_test3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_test3.xlsx")

In [9]:
X_train5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_train5.xlsx")
y_train5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_train5.xlsx")

X_test5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_test5.xlsx")
y_test5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_test5.xlsx")

In [10]:
X_train3 = X_train3.iloc[: , 1:]
y_train3 = y_train3.iloc[: , 1:]

X_test3 = X_test3.iloc[: , 1:]
y_test3 = y_test3.iloc[: , 1:]

In [11]:
X_train5 = X_train5.iloc[: , 1:]
y_train5 = y_train5.iloc[: , 1:]

X_test5 = X_test5.iloc[: , 1:]
y_test5 = y_test5.iloc[: , 1:]

In [12]:
import sklearn
assert sklearn.__version__ >= "0.20"

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE

# SKLEARN RESAMPLE

In [13]:
df_train3 = pd.concat([X_train3, y_train3], axis=1)
df_train_hold3 = df_train3[(df_train3['decision']==0)] 
df_train_buy3 = df_train3[(df_train3['decision']==-1)] 
df_train_sell3 = df_train3[(df_train3['decision']==1)] 

# upsample buy and sell class
df_train_buy_upsampled3 = resample(df_train_buy3, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold3)) # to match majority class

df_train_sell_upsampled3 = resample(df_train_sell3, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold3)) # to match majority class

# Combine majority class with upsampled minority classes
df_train_upsampled3 = pd.concat([df_train_buy_upsampled3, df_train_sell_upsampled3, df_train_hold3])
X_train_upsampled3, y_train_upsampled3 = df_train_upsampled3.drop(columns=['decision']), df_train_upsampled3['decision']
y_train_upsampled3.value_counts()

 0    1264
-1    1264
 1    1264
Name: decision, dtype: int64

In [14]:
df_train5 = pd.concat([X_train5, y_train5], axis=1)
df_train_hold5 = df_train5[(df_train3['decision']==0)] 
df_train_buy5 = df_train5[(df_train3['decision']==-1)] 
df_train_sell5 = df_train5[(df_train3['decision']==1)] 

# upsample buy and sell class
df_train_buy_upsampled5 = resample(df_train_buy5, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold5)) # to match majority class

df_train_sell_upsampled5 = resample(df_train_sell5, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold5)) # to match majority class

# Combine majority class with upsampled minority classes
df_train_upsampled5 = pd.concat([df_train_buy_upsampled5, df_train_sell_upsampled5, df_train_hold5])
X_train_upsampled5, y_train_upsampled5 = df_train_upsampled5.drop(columns=['decision']), df_train_upsampled5['decision']
y_train_upsampled5.value_counts()

 0    2957
 1     570
-1     265
Name: decision, dtype: int64

# SMOTE RESAMPLE

In [15]:
X_train3[X_train3.isnull().any(axis=1)]

Empty DataFrame
Columns: [adj_close, reddit_pos_both, reddit_neg_both, reddit_neu_both, nyt_pos, nyt_neg, nyt_neu, quarterly_gdp_actual, monthly_cpi_actual, monthly_st_ir_actual, monthly_unemployment_actual]
Index: []

In [16]:
sm3 = SMOTE(sampling_strategy='not majority')
X_train_oversampled3, y_train_oversampled3 = sm3.fit_resample(X_train3, y_train3)
y_train_oversampled3.value_counts()

decision
-1          1264
 0          1264
 1          1264
dtype: int64

In [17]:
sm5 = SMOTE(sampling_strategy='not majority')
X_train_oversampled5, y_train_oversampled5 = sm5.fit_resample(X_train5, y_train5)
y_train_oversampled5.value_counts()

decision
-1          1436
 0          1436
 1          1436
dtype: int64

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# Decision Tree Classifier

In [19]:
tree = DecisionTreeClassifier(max_depth=2, random_state=42)

## 3% Target Threshold

In [20]:
tree.fit(X_train3, y_train3)

DecisionTreeClassifier(max_depth=2, random_state=42)

### Predicting on train set (3%)

In [21]:
y_predict_train3 = tree.predict(X_train3)
confusion_matrix_train3 = confusion_matrix(y_train3, y_predict_train3)
accuracy_score_train3 = accuracy_score(y_train3, y_predict_train3)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3))

Confusion_Matrix:
[[   0  144    3]
 [   0 1262    2]
 [   0   76   24]]
Accuracy_Score: 0.8510919920582396



In [22]:
diagonals_train3 = confusion_matrix_train3.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_train3))

Number of Rows Prediction Correctly: 1286



In [23]:
precision_train3 = precision_score(y_train3, y_predict_train3, average = "weighted")
precision_train3

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.7671213064883918

In [24]:
recall_train3 = recall_score(y_train3, y_predict_train3, average = "weighted")
recall_train3 

0.8510919920582396

### Predicting on test set (3%)

In [25]:
y_predict_test3 = tree.predict(X_test3)
confusion_matrix_test3 = confusion_matrix(y_test3, y_predict_test3)
accuracy_score_test3 = accuracy_score(y_test3, y_predict_test3)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3))

Confusion_Matrix:
[[ 0 39  0]
 [ 0 86  0]
 [ 0 43  0]]
Accuracy_Score: 0.5119047619047619



In [26]:
diagonals_test3 = confusion_matrix_test3.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3))

Number of Rows Prediction Correctly: 86



In [27]:
precision_test3 = precision_score(y_test3, y_predict_test3, average = "weighted")
precision_test3

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.26204648526077096

In [28]:
recall_test3 = recall_score(y_test3, y_predict_test3, average = "weighted")
recall_test3 

0.5119047619047619

## SKLearn Resample 3% 

In [29]:
tree.fit(X_train_upsampled3, y_train_upsampled3)

DecisionTreeClassifier(max_depth=2, random_state=42)

### [SKLEARN RESAMPLE] Predicting on train set (3%)

In [30]:
y_predict_train3sk = tree.predict(X_train_upsampled3)
confusion_matrix_train3sk = confusion_matrix(y_train_upsampled3, y_predict_train3sk)
accuracy_score_train3sk = accuracy_score(y_train_upsampled3, y_predict_train3sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3sk))

Confusion_Matrix:
[[544 565 155]
 [234 830 200]
 [147 261 856]]
Accuracy_Score: 0.5880801687763713



In [31]:
skdiagonals_train3sk = confusion_matrix_train3sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train3sk))

Number of Rows Prediction Correctly: 2230



In [32]:
precision_train3sk = precision_score(y_train_upsampled3, y_predict_train3sk, average = "weighted")
precision_train3sk

0.5987232257928413

In [33]:
recall_train3sk = recall_score(y_train_upsampled3, y_predict_train3sk, average = "weighted")
recall_train3sk

0.5880801687763713

### [SKLEARN RESAMPLE] Predicting on test set (3%)

In [34]:
y_predict_test3sk = tree.predict(X_test3)
confusion_matrix_test3sk = confusion_matrix(y_test3, y_predict_test3sk)
accuracy_score_test3sk = accuracy_score(y_test3, y_predict_test3sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3sk))

Confusion_Matrix:
[[ 0 35  4]
 [ 0 72 14]
 [ 0 32 11]]
Accuracy_Score: 0.49404761904761907



In [35]:
diagonals_test3sk = confusion_matrix_test3sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3sk))

Number of Rows Prediction Correctly: 83



In [36]:
precision_test3sk = precision_score(y_test3, y_predict_test3sk, average = "weighted")
precision_test3sk 

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.36224468700901347

In [37]:
recall_test3sk = recall_score(y_test3, y_predict_test3sk, average = "weighted")
recall_test3sk 

0.49404761904761907

## SMOTE Resample 3% 

In [38]:
tree.fit(X_train_oversampled3, y_train_oversampled3)

DecisionTreeClassifier(max_depth=2, random_state=42)

### [SMOTE] Predicting on train set (3%)

In [39]:
y_predict_train3sm = tree.predict(X_train_oversampled3)
confusion_matrix_train3sm = confusion_matrix(y_train_oversampled3, y_predict_train3sm)
accuracy_score_train3sm = accuracy_score(y_train_oversampled3, y_predict_train3sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3sm))

Confusion_Matrix:
[[582 543 139]
 [165 764 335]
 [159 180 925]]
Accuracy_Score: 0.5988924050632911



In [40]:
skdiagonals_train3sm = confusion_matrix_train3sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train3sm))

Number of Rows Prediction Correctly: 2271



In [41]:
precision_train3sm = precision_score(y_train_oversampled3, y_predict_train3sm, average = "weighted")
precision_train3sm

0.6057856047980146

In [42]:
recall_train3sm = recall_score(y_train_oversampled3, y_predict_train3sm, average = "weighted")
recall_train3sm

0.5988924050632911

### [SMOTE] Predicting on test set (3%)

In [43]:
y_predict_test3sm = tree.predict(X_test3)
confusion_matrix_test3sm = confusion_matrix(y_test3, y_predict_test3sm)
accuracy_score_test3sm = accuracy_score(y_test3, y_predict_test3sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3sm))

Confusion_Matrix:
[[ 0 35  4]
 [ 0 63 23]
 [ 0 28 15]]
Accuracy_Score: 0.4642857142857143



In [44]:
diagonals_test3sm = confusion_matrix_test3sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3sm))

Number of Rows Prediction Correctly: 78



In [45]:
precision_test3sm = precision_score(y_test3, y_predict_test3sm, average = "weighted")
precision_test3sm

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.3473639455782313

In [46]:
recall_test3sm= recall_score(y_test3, y_predict_test3sm, average = "weighted")
recall_test3sm

0.4642857142857143

## 5% Target threshold

In [47]:
tree.fit(X_train5, y_train5)

DecisionTreeClassifier(max_depth=2, random_state=42)

### Predicting on train set (5%)

In [48]:
y_predict_train5 = tree.predict(X_train5)
confusion_matrix_train5 = confusion_matrix(y_train5, y_predict_train5)
accuracy_score_train5 = accuracy_score(y_train5, y_predict_train5)
print("Confusion_Matrix (5%):\n{}"
      .format(confusion_matrix_train5))
print("Accuracy_Score (5%): {}\n"
      .format(accuracy_score_train5))

Confusion_Matrix (5%):
[[   0   29    1]
 [   0 1426   10]
 [   0   27   18]]
Accuracy_Score (5%): 0.9556585043017869



In [49]:
diagonals_train5 = confusion_matrix_train5.diagonal().sum()
print("Number of Rows Prediction Correctly (5%): {}\n"
      .format(diagonals_train5))

Number of Rows Prediction Correctly (5%): 1444



In [50]:
TP_train5 = confusion_matrix_train5[1, 1]
TN_train5 = confusion_matrix_train5[0, 0]
FP_train5 = confusion_matrix_train5[0, 1]
FN_train5 = confusion_matrix_train5[1, 0]

In [51]:
precision_train5 = precision_score(y_train5, y_predict_train5, average = "weighted")
precision_train5

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.9329379391897333

In [52]:
recall_train5 = recall_score(y_train5, y_predict_train5, average = "weighted")
recall_train5

0.9556585043017869

### Predicting on test set (5%)

In [53]:
y_predict_test5 = tree.predict(X_test5)
confusion_matrix_test5 = confusion_matrix(y_test5, y_predict_test5)
accuracy_score_test5 = accuracy_score(y_test5, y_predict_test5)
print("Confusion_Matrix (5%):\n{}"
      .format(confusion_matrix_test5))
print("Accuracy_Score (5%): {}\n"
      .format(accuracy_score_test5))

Confusion_Matrix (5%):
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score (5%): 0.8154761904761905



In [54]:
diagonals_test5 = confusion_matrix_test5.diagonal().sum()
print("Number of Rows Prediction Correctly (5%): {}\n"
      .format(diagonals_test5))

Number of Rows Prediction Correctly (5%): 137



In [55]:
precision_test5 = precision_score(y_test5, y_predict_test5, average = "weighted")
precision_test5 

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6650014172335601

In [56]:
recall_test5 = recall_score(y_test5, y_predict_test5, average = "weighted")
recall_test5 

0.8154761904761905

## SKLearn Resample 5% 

In [57]:
tree.fit(X_train_upsampled5, y_train_upsampled5)

DecisionTreeClassifier(max_depth=2, random_state=42)

### [SKLEARN RESAMPLE] Predicting on train set (5%)

In [58]:
y_predict_train5sk = tree.predict(X_train_upsampled5)
confusion_matrix_train5sk = confusion_matrix(y_train_upsampled5, y_predict_train5sk)
accuracy_score_train5sk = accuracy_score(y_train_upsampled5, y_predict_train5sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train5sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train5sk))

Confusion_Matrix:
[[  50  202   13]
 [  21 2812  124]
 [   0  248  322]]
Accuracy_Score: 0.8396624472573839



In [59]:
skdiagonals_train5sk = confusion_matrix_train5sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train5sk))

Number of Rows Prediction Correctly: 3184



In [60]:
precision_train5sk = precision_score(y_train_upsampled5, y_predict_train5sk, average = "weighted")
precision_train5sk

0.8268893494757755

In [61]:
recall_train5sk = recall_score(y_train_upsampled5, y_predict_train5sk, average = "weighted")
recall_train5sk

0.8396624472573839

### [SKLEARN RESAMPLE] Predicting on test set (5%)

In [62]:
y_predict_test5sk = tree.predict(X_test5)
confusion_matrix_test5sk = confusion_matrix(y_test5, y_predict_test5sk)
accuracy_score_test5sk = accuracy_score(y_test5, y_predict_test5sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test5sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test5sk))

Confusion_Matrix:
[[  0   9   1]
 [  0 134   3]
 [  0  20   1]]
Accuracy_Score: 0.8035714285714286



In [63]:
diagonals_test5sk = confusion_matrix_test5sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test5sk))

Number of Rows Prediction Correctly: 135



In [64]:
precision_test5sk = precision_score(y_test5, y_predict_test5sk, average = "weighted")
precision_test5sk 

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6953914694712241

In [65]:
recall_test5sk = recall_score(y_test5, y_predict_test5sk, average = "weighted")
recall_test5sk 

0.8035714285714286

## SMOTE Resample 5% 

In [66]:
tree.fit(X_train_oversampled5, y_train_oversampled5)

DecisionTreeClassifier(max_depth=2, random_state=42)

### [SMOTE] Predicting on train set (5%)

In [67]:
y_predict_train5sm = tree.predict(X_train_oversampled5)
confusion_matrix_train5sm = confusion_matrix(y_train_oversampled5, y_predict_train5sm)
accuracy_score_train5sm = accuracy_score(y_train_oversampled5, y_predict_train5sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train5sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train5sm))

Confusion_Matrix:
[[ 626  648  162]
 [  29 1185  222]
 [  10  186 1240]]
Accuracy_Score: 0.708217270194986



In [68]:
skdiagonals_train5sm = confusion_matrix_train5sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train5sm))

Number of Rows Prediction Correctly: 3051



In [69]:
precision_train5sm = precision_score(y_train_oversampled5, y_predict_train5sm, average = "weighted")
precision_train5sm

0.7639414671330167

In [70]:
recall_train5sm = recall_score(y_train_oversampled5, y_predict_train5sm, average = "weighted")
recall_train5sm

0.708217270194986

### [SMOTE] Predicting on test set (5%)

In [71]:
y_predict_test5sm = tree.predict(X_test5)
confusion_matrix_test5sm = confusion_matrix(y_test5, y_predict_test5sm)
accuracy_score_test5sm = accuracy_score(y_test5, y_predict_test5sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test5sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test5sm))

Confusion_Matrix:
[[  0   8   2]
 [  0 120  17]
 [  0  13   8]]
Accuracy_Score: 0.7619047619047619



In [72]:
diagonals_test5sm = confusion_matrix_test5sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test5sm))

Number of Rows Prediction Correctly: 128



In [73]:
precision_test5sm = precision_score(y_test5, y_predict_test5sm, average = "weighted")
precision_test5sm

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.7310593268040076

In [74]:
recall_test5sm= recall_score(y_test5, y_predict_test5sm, average = "weighted")
recall_test5sm

0.7619047619047619

In [77]:
dftree = pd.DataFrame({
    'model': ['Decision Tree 3%', 'Decision Tree 3% SK Resample', 'Decision Tree 3% SMOTE', 'Decision Tree 5%', 'Decision Tree 5% SK Resample', 'Decision Tree 5% SMOTE',],
    'accuracy': [accuracy_score_test3,accuracy_score_test3sk, accuracy_score_test3sm, accuracy_score_test5,accuracy_score_test5sk, accuracy_score_test5sm],
    'recall': [recall_test3, recall_test3sk, recall_test3sm, recall_test5, recall_test5sk, recall_test5sm],
    'precision': [precision_test3, precision_test3sk, precision_test3sm, precision_test5, precision_test5sk, precision_test5sm],
})

dftree

model  accuracy    recall  precision
0              Decision Tree 3%  0.511905  0.511905   0.262046
1  Decision Tree 3% SK Resample  0.494048  0.494048   0.362245
2        Decision Tree 3% SMOTE  0.464286  0.464286   0.347364
3              Decision Tree 5%  0.815476  0.815476   0.665001
4  Decision Tree 5% SK Resample  0.803571  0.803571   0.695391
5        Decision Tree 5% SMOTE  0.761905  0.761905   0.731059