In [1]:
import pandas as pd 
import numpy as np

In [2]:
X_train = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_train.xlsx")
y_train = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_train.xlsx")

X_test = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_test.xlsx")
y_test = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_test.xlsx")

In [3]:
X_train = X_train.iloc[: , 1:]
y_train = y_train.iloc[: , 1:]

X_test = X_test.iloc[: , 1:]
y_test = y_test.iloc[: , 1:]

In [4]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1511, 11), (168, 11), (1511, 1), (168, 1))

In [5]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [6]:
tree = DecisionTreeClassifier(max_depth=2, random_state=42)
tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2, random_state=42)

# Predict on Train Set

In [7]:
y_predict_train = tree.predict(X_train)
confusion_matrix_train = confusion_matrix(y_train, y_predict_train)
accuracy_score_train = accuracy_score(y_train, y_predict_train)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train))

Confusion_Matrix:
[[   0   29    1]
 [   0 1426   10]
 [   0   27   18]]
Accuracy_Score: 0.9556585043017869



In [8]:
diagonals_train = confusion_matrix_train.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_train))

Number of Rows Prediction Correctly: 1444



In [9]:
TP_train = confusion_matrix_train[1, 1]
TN_train = confusion_matrix_train[0, 0]
FP_train = confusion_matrix_train[0, 1]
FN_train = confusion_matrix_train[1, 0]

In [10]:
precision_train = print(FP_train / (TN_train + FP_train))
precision_train 

1.0


In [11]:
recall_train = print(TP_train / (TP_train + FN_train))
recall_train 

1.0


# Predict on Test Set

In [12]:
y_predict_test = tree.predict(X_test)
confusion_matrix_test = confusion_matrix(y_test, y_predict_test)
accuracy_score_test = accuracy_score(y_test, y_predict_test)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test))

Confusion_Matrix:
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score: 0.8154761904761905



In [13]:
diagonals_test = confusion_matrix_test.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test))

Number of Rows Prediction Correctly: 137



In [14]:
TP_test = confusion_matrix_test[1, 1]
TN_test = confusion_matrix_test[0, 0]
FP_test = confusion_matrix_test[0, 1]
FN_test = confusion_matrix_test[1, 0]

In [15]:
precision_test = print(FP_test / (TN_test + FP_test))
precision_test 

1.0


In [16]:
recall_test = print(TP_test / (TP_test + FN_test))
recall_test 

1.0
