In [1]:
import datetime
import pandas as pd
import numpy as np
import yfinance as yf
from sklearn.linear_model import LogisticRegression

from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import ADASYN

from scipy.stats import loguniform, uniform, randint
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

c:\Python39\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.6) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "


In [2]:
logreg_distribution = {'penalty': ['l1', 'l2'], 'C': loguniform(0.001, 100), 'solver': ['newton-cg','sag','saga','lbfgs']}

Import data

In [3]:
X_train_3perc_lag3 = pd.read_excel("data/model_inputs2/x_train_3perc_lag3.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
X_test_3perc_lag3 = pd.read_excel("data/model_inputs2/x_test_3perc_lag3.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
y_train_3perc_lag3 = pd.read_excel("data/model_inputs2/y_train_3perc_lag3.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
y_test_3perc_lag3 = pd.read_excel("data/model_inputs2/y_test_3perc_lag3.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')

X_train_3perc_lag7 = pd.read_excel("data/model_inputs2/x_train_3perc_lag7.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
X_test_3perc_lag7 = pd.read_excel("data/model_inputs2/x_test_3perc_lag7.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
y_train_3perc_lag7 = pd.read_excel("data/model_inputs2/y_train_3perc_lag7.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
y_test_3perc_lag7 = pd.read_excel("data/model_inputs2/y_test_3perc_lag7.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')

X_train_5perc_lag3 = pd.read_excel("data/model_inputs2/x_train_5perc_lag3.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
X_test_5perc_lag3 = pd.read_excel("data/model_inputs2/x_test_5perc_lag3.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
y_train_5perc_lag3 = pd.read_excel("data/model_inputs2/y_train_5perc_lag3.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
y_test_5perc_lag3 = pd.read_excel("data/model_inputs2/y_test_5perc_lag3.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')

X_train_5perc_lag7 = pd.read_excel("data/model_inputs2/x_train_5perc_lag7.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
X_test_5perc_lag7 = pd.read_excel("data/model_inputs2/x_test_5perc_lag7.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
y_train_5perc_lag7 = pd.read_excel("data/model_inputs2/y_train_5perc_lag7.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')
y_test_5perc_lag7 = pd.read_excel("data/model_inputs2/y_test_5perc_lag7.xlsx").rename(columns={'Unnamed: 0':'date'}).set_index('date')

Oversampling methods

In [4]:
def smote(X_train, y_train):
    sm = SMOTE(sampling_strategy='not majority')
    X_train_oversampled, y_train_oversampled = sm.fit_resample(X_train, y_train)
    return X_train_oversampled, y_train_oversampled

def random_oversampler(X_train, y_train):
    oversample = RandomOverSampler(sampling_strategy='not majority')
    X_over, y_over = oversample.fit_resample(X_train, y_train)
    return X_over, y_over

def adasyn(X_train, y_train):
    ada = ADASYN(sampling_strategy = 'not majority')
    X_resampled, y_resampled = ADASYN().fit_resample(X_train, y_train)
    return X_resampled, y_resampled

12 combinations without tuning

In [5]:
perc_col, lag_col, oversampling_method, accuracy, precision, recall, f1, pred_count = [], [], [], [], [], [], [], []

for perc in ['3perc', '5perc']:
    for lag in [3, 7]:
        for oversampling in ['smote', 'random_oversampler', 'adasyn']:
            X_train = eval(f'X_train_{perc}_lag{lag}')
            X_test = eval(f'X_test_{perc}_lag{lag}')
            y_train = eval(f'y_train_{perc}_lag{lag}')
            y_test = eval(f'y_test_{perc}_lag{lag}')

            # oversampling
            if oversampling == 'smote':
                X_train_oversampled, y_train_oversampled = smote(X_train, y_train)
            elif oversampling == 'random_oversampler':
                X_train_oversampled, y_train_oversampled = random_oversampler(X_train, y_train)
            else:
                X_train_oversampled, y_train_oversampled = adasyn(X_train, y_train)

            # fit and predict
            logreg = LogisticRegression()
            pred = logreg.fit(X_train_oversampled, y_train_oversampled).predict(X_test)

            # update columns
            perc_col.append(perc)
            lag_col.append(lag)
            oversampling_method.append(oversampling)
            accuracy.append(accuracy_score(y_test, pred))
            precision.append(precision_score(y_test, pred, average='weighted'))
            recall.append(recall_score(y_test, pred, average='weighted'))
            f1.append(f1_score(y_test, pred, average='weighted'))
            pred_count.append(dict(pd.Series(pred).value_counts().sort_index()))

results_no_tuning = pd.DataFrame({
    'model': "Logistic Regression",
    'perc_threshold': perc_col,
    'lag': lag_col,
    'oversampling': oversampling_method,
    'accuracy': accuracy,
    'precision': precision,
    'recall': recall,
    'f1': f1,
    'pred_count': pred_count
})
results_no_tuning

model perc_threshold  lag        oversampling  accuracy  \
0   Logistic Regression          3perc    3               smote  0.464286   
1   Logistic Regression          3perc    3  random_oversampler  0.476190   
2   Logistic Regression          3perc    3              adasyn  0.440476   
3   Logistic Regression          3perc    7               smote  0.339286   
4   Logistic Regression          3perc    7  random_oversampler  0.327381   
5   Logistic Regression          3perc    7              adasyn  0.327381   
6   Logistic Regression          5perc    3               smote  0.720238   
7   Logistic Regression          5perc    3  random_oversampler  0.803571   
8   Logistic Regression          5perc    3              adasyn  0.708333   
9   Logistic Regression          5perc    7               smote  0.601190   
10  Logistic Regression          5perc    7  random_oversampler  0.648810   
11  Logistic Regression          5perc    7              adasyn  0.601190   

    precision    recall        f1              pred_count  
0    0.492615  0.464286  0.462147  {-1: 70, 0: 59, 1: 39}  
1    0.481255  0.476190  0.475993  {-1: 55, 0: 79, 1: 34}  
2    0.481883  0.440476  0.434101  {-1: 82, 0: 53, 1: 33}  
3    0.413697  0.339286  0.332507  {-1: 29, 0: 43, 1: 96}  
4    0.380357  0.327381  0.318608  {-1: 31, 0: 46, 1: 91}  
5    0.377275  0.327381  0.318727  {-1: 46, 0: 42, 1: 80}  
6    0.742433  0.720238  0.722882  {-1: 9, 0: 140, 1: 19}  
7    0.749008  0.803571  0.765297   {-1: 9, 0: 156, 1: 3}  
8    0.729507  0.708333  0.709673  {-1: 8, 0: 140, 1: 20}  
9    0.669772  0.601190  0.628185  {-1: 1, 0: 120, 1: 47}  
10   0.684398  0.648810  0.656932  {-1: 4, 0: 134, 1: 30}  
11   0.653771  0.601190  0.623046         {0: 124, 1: 44}

Tuning for 5perc, lag7, random_oversampler

In [6]:
perc_col, lag_col, oversampling_method, param, accuracy, precision, recall, f1 = [], [], [], [], [], [], [], []

perc = '5perc'
lag = 7
oversampling = 'random_oversampler'
X_train = eval(f'X_train_{perc}_lag{lag}')
X_test = eval(f'X_test_{perc}_lag{lag}')
y_train = eval(f'y_train_{perc}_lag{lag}')
y_test = eval(f'y_test_{perc}_lag{lag}')

# oversampling
if oversampling == 'smote':
    X_train_oversampled, y_train_oversampled = smote(X_train, y_train)
elif oversampling == 'random_oversampler':
    X_train_oversampled, y_train_oversampled = random_oversampler(X_train, y_train)
else:
    X_train_oversampled, y_train_oversampled = adasyn(X_train, y_train)

# tuning
logreg = LogisticRegression()
logreg_clf = RandomizedSearchCV(logreg, logreg_distribution, n_iter=100, scoring=['accuracy', 'recall_weighted', 'precision_weighted', 'f1_weighted'], refit='f1_weighted', random_state=42)
logreg_search = logreg_clf.fit(X_train_oversampled, y_train_oversampled)

# update columns
perc_col.append([perc]*100)
lag_col.append([lag]*100)
oversampling_method.append([oversampling]*100)
param.append(logreg_search.cv_results_['params'])
accuracy.append(logreg_search.cv_results_['mean_test_accuracy'])
precision.append(logreg_search.cv_results_['mean_test_precision_weighted'])
recall.append(logreg_search.cv_results_['mean_test_recall_weighted'])
f1.append(logreg_search.cv_results_['mean_test_f1_weighted'])

In [7]:
results = pd.DataFrame({
    'model': "Logistic Regression",
    'perc_threshold': np.array(perc_col).flatten(),
    'lag': np.array(lag_col).flatten(),
    'oversampling': np.array(oversampling_method).flatten(),
    'parameters': np.array(param).flatten(),
    'accuracy': np.array(accuracy).flatten(),
    'precision': np.array(precision).flatten(),
    'recall': np.array(recall).flatten(),
    'f1': np.array(f1).flatten(),
}).sort_values(by="f1", ascending=False).reset_index(drop=True)

In [8]:
results.head(10)

model perc_threshold  lag        oversampling  \
0  Logistic Regression          5perc    7  random_oversampler   
1  Logistic Regression          5perc    7  random_oversampler   
2  Logistic Regression          5perc    7  random_oversampler   
3  Logistic Regression          5perc    7  random_oversampler   
4  Logistic Regression          5perc    7  random_oversampler   
5  Logistic Regression          5perc    7  random_oversampler   
6  Logistic Regression          5perc    7  random_oversampler   
7  Logistic Regression          5perc    7  random_oversampler   
8  Logistic Regression          5perc    7  random_oversampler   
9  Logistic Regression          5perc    7  random_oversampler   

                                          parameters  accuracy  precision  \
0  {'C': 0.006026889128682509, 'penalty': 'l1', '...  0.719571   0.733531   
1  {'C': 0.001339971723117972, 'penalty': 'l1', '...  0.714689   0.732095   
2  {'C': 0.0010656401760606444, 'penalty': 'l1', ...  0.712832   0.729418   
3  {'C': 70.45683638454503, 'penalty': 'l2', 'sol...  0.668032   0.631138   
4  {'C': 4.446628955475449, 'penalty': 'l2', 'sol...  0.668033   0.631469   
5  {'C': 7.264803074826727, 'penalty': 'l2', 'sol...  0.668033   0.631331   
6  {'C': 1.146210740342503, 'penalty': 'l2', 'sol...  0.667569   0.631294   
7  {'C': 1.11640473527937, 'penalty': 'l2', 'solv...  0.667569   0.631212   
8  {'C': 3.4220529032706932, 'penalty': 'l1', 'so...  0.667801   0.631100   
9  {'C': 6.366859160799431, 'penalty': 'l2', 'sol...  0.667801   0.631054   

     recall        f1  
0  0.719571  0.716058  
1  0.714689  0.711190  
2  0.712832  0.709442  
3  0.668032  0.642208  
4  0.668033  0.641994  
5  0.668033  0.641931  
6  0.667569  0.641751  
7  0.667569  0.641718  
8  0.667801  0.641674  
9  0.667801  0.641655

Best Model

In [9]:
best_params, best_perc, best_lag, best_oversampling = results.iloc[0]['parameters'], results.iloc[0]['perc_threshold'], results.iloc[0]['lag'], results.iloc[0]['oversampling']
best_model = LogisticRegression(**best_params)
X_train, y_train, x_test, y_test = eval(f'X_train_{best_perc}_lag{best_lag}'), eval(f'y_train_{best_perc}_lag{best_lag}'), eval(f'X_test_{best_perc}_lag{best_lag}'), eval(f'y_test_{best_perc}_lag{best_lag}')

if best_oversampling == 'smote':
    X_train_oversampled, y_train_oversampled = smote(X_train, y_train)
elif best_oversampling == 'random_oversampler':
    X_train_oversampled, y_train_oversampled = random_oversampler(X_train, y_train)
else:
    X_train_oversampled, y_train_oversampled = adasyn(X_train, y_train)

best_model.fit(X_train_oversampled, y_train_oversampled)
best_model

LogisticRegression(C=0.006026889128682509, penalty='l1', solver='saga')

In [10]:
def print_results(actual, predictions):
    print(f"accuracy: {accuracy_score(actual, predictions)}")
    print(f"precision: {precision_score(actual, predictions, average='weighted')}")
    print(f"recall: {recall_score(actual, predictions, average='weighted')}")
    print(f"f1: {f1_score(actual, predictions, average='weighted')}")
    print(f"confusion matrix:\n{confusion_matrix(actual, predictions)}")

Predict on test set

In [11]:
test_pred = best_model.predict(X_test)
print_results(y_test, test_pred)

accuracy: 0.6785714285714286
precision: 0.7302295918367346
recall: 0.6785714285714286
f1: 0.6933108501552796
confusion matrix:
[[ 12   9   0]
 [ 34 102   1]
 [  2   8   0]]


Predict on full data

In [12]:
X_full = pd.concat([X_train, X_test])
y_full = pd.concat([y_train, y_test])

full_pred = best_model.predict(X_full)
print_results(y_full, full_pred)

accuracy: 0.7623585467540203
precision: 0.9234567003493235
recall: 0.7623585467540203
f1: 0.8227292220950283
confusion matrix:
[[  49   15    2]
 [ 200 1213  160]
 [   6   16   18]]


Business Metric

In [25]:
whole_df_x = pd.concat([X_train, X_test])
whole_df_x.shape

(1679, 11)

In [28]:
whole_df_x['year'] = whole_df_x.index.year

In [38]:
business_metric_results = pd.DataFrame(columns=['exp_strategy_annual_return', 'exp_benchmark_annual_return'])

for year in [2016, 2017, 2018, 2019, 2020, 2021, 2022]:
    year_data = whole_df_x[whole_df_x['year'] == year]
    # year_data = year_data.set_index('index')
    year_data = year_data.drop(['year'], axis = 1)
    predict_x = best_model.predict(np.array(year_data)) 
    # predictions = np.argmax(predict_x,axis=1)
    predictions = predict_x

    df_pred = pd.DataFrame({'prediction':predictions}, index=year_data.index)
    df_pred = df_pred.replace({-1:1, 1:-1}) # convert classes to buy hold sell
    dates = df_pred.index

    if year == 2022:
        end_date = "2022-09-02"
    else:
        end_date = str(year+1) + "-01-01"
    df_prices = yf.download("^GSPC", start=dates[0], end=end_date)[['Adj Close']]

    # create positions column
    positions = []
    prev = 0
    for i in range(len(df_pred)):
        if df_pred.iloc[i]['prediction'] == 0:
            positions.append(prev)
        else:
            prev = df_pred.iloc[i]['prediction']
            positions.append(prev)

    df_business = pd.DataFrame()
    df_business['stock_daily_log_return'] = np.log(df_prices /df_prices.shift(1))['Adj Close']
    df_business['prediction'] = df_pred['prediction']
    df_business['position'] = positions
    df_business['benchmark'] = 1 # long and hold strategy
    df_business["strategy_Returns"] = df_business["stock_daily_log_return"] * df_business["position"].shift(1)
    df_business["benchmark_Returns"] = df_business["stock_daily_log_return"] * df_business["benchmark"].shift(1)

    # Annual Mean Returns or Expected returns
    expected_strategy_annual_return = np.exp(df_business['strategy_Returns'].mean() * 252) - 1 
    expected_benchmark_annual_return = np.exp(df_business['benchmark_Returns'].mean() * 252) - 1 
    business_metric_results.loc[year] = [expected_strategy_annual_return, expected_benchmark_annual_return]
    # print(f'Expected Annual Returns: Strategy: {round(expected_strategy_annual_return*100, 2)}%  |  Stock: {round(expected_benchmark_annual_return*100, 2)}%')

business_metric_results

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


exp_strategy_annual_return  exp_benchmark_annual_return
2016                    0.164536                     0.112846
2017                    0.108954                     0.185753
2018                   -0.113091                    -0.070634
2019                    0.288443                     0.288443
2020                   -0.496283                     0.152929
2021                    0.264121                     0.289230
2022                   -0.058229                    -0.249185