In [1]:
import pandas as pd 
import numpy as np

In [2]:
X_train = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_train.xlsx")
y_train = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_train.xlsx")

X_test = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_test.xlsx")
y_test = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_test.xlsx")

In [3]:
X_train = X_train.iloc[: , 1:]
y_train = y_train.iloc[: , 1:]

X_test = X_test.iloc[: , 1:]
y_test = y_test.iloc[: , 1:]

In [4]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1511, 11), (168, 11), (1511, 1), (168, 1))

In [5]:
import sklearn
assert sklearn.__version__ >= "0.20"

np.random.seed(42)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [6]:
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, random_state=42)
rnd_clf.fit(X_train, y_train)

C:\Users\chloe\AppData\Local\Temp\ipykernel_27180\3105075459.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rnd_clf.fit(X_train, y_train)


RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, random_state=42)

# Predicting on train set

In [7]:
y_predict_train = rnd_clf.predict(X_train)
confusion_matrix_train = confusion_matrix(y_train, y_predict_train)
accuracy_score_train = accuracy_score(y_train, y_predict_train)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train))

Confusion_Matrix:
[[   8   22    0]
 [   0 1435    1]
 [   0   27   18]]
Accuracy_Score: 0.9669093315684977



In [8]:
diagonals_train = confusion_matrix_train.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_train))

Number of Rows Prediction Correctly: 1461



In [9]:
TP_train = confusion_matrix_train[1, 1]
TN_train = confusion_matrix_train[0, 0]
FP_train = confusion_matrix_train[0, 1]
FN_train = confusion_matrix_train[1, 0]

In [10]:
precision_train = print(FP_train / (TN_train + FP_train))
precision_train 

0.7333333333333333


In [11]:
recall_train = print(TP_train / (TP_train + FN_train))
recall_train 

1.0


# Predicting on test set

In [12]:
y_predict_test = rnd_clf.predict(X_test)
confusion_matrix_test = confusion_matrix(y_test, y_predict_test)
accuracy_score_test = accuracy_score(y_test, y_predict_test)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test))

Confusion_Matrix:
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score: 0.8154761904761905



In [13]:
diagonals_test = confusion_matrix_test.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test))

Number of Rows Prediction Correctly: 137



In [14]:
TP_test = confusion_matrix_test[1, 1]
TN_test = confusion_matrix_test[0, 0]
FP_test = confusion_matrix_test[0, 1]
FN_test = confusion_matrix_test[1, 0]

In [15]:
precision_test = print(FP_test / (TN_test + FP_test))
precision_test 

1.0


In [16]:
recall_test = print(TP_test / (TP_test + FN_test))
recall_test 

1.0
