In [77]:
import pandas as pd 
import numpy as np

In [78]:
X_train3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_train3.xlsx")
y_train3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_train3.xlsx")

X_test3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_test3.xlsx")
y_test3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_test3.xlsx")

In [79]:
X_train5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_train5.xlsx")
y_train5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_train5.xlsx")

X_test5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_test5.xlsx")
y_test5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_test5.xlsx")

In [80]:
X_train3 = X_train3.iloc[: , 1:]
y_train3 = y_train3.iloc[: , 1:]

X_test3 = X_test3.iloc[: , 1:]
y_test3 = y_test3.iloc[: , 1:]

In [81]:
X_train5 = X_train5.iloc[: , 1:]
y_train5 = y_train5.iloc[: , 1:]

X_test5 = X_test5.iloc[: , 1:]
y_test5 = y_test5.iloc[: , 1:]

In [82]:
import sklearn
assert sklearn.__version__ >= "0.20"

from sklearn.svm import SVC
from sklearn import svm
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE

# SKLEARN RESAMPLE

In [83]:
df_train3 = pd.concat([X_train3, y_train3], axis=1)
df_train_hold3 = df_train3[(df_train3['decision']==0)] 
df_train_buy3 = df_train3[(df_train3['decision']==-1)] 
df_train_sell3 = df_train3[(df_train3['decision']==1)] 

# upsample buy and sell class
df_train_buy_upsampled3 = resample(df_train_buy3, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold3)) # to match majority class

df_train_sell_upsampled3 = resample(df_train_sell3, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold3)) # to match majority class

# Combine majority class with upsampled minority classes
df_train_upsampled3 = pd.concat([df_train_buy_upsampled3, df_train_sell_upsampled3, df_train_hold3])
X_train_upsampled3, y_train_upsampled3 = df_train_upsampled3.drop(columns=['decision']), df_train_upsampled3['decision']
y_train_upsampled3.value_counts()

 0    1264
-1    1264
 1    1264
Name: decision, dtype: int64

In [84]:
df_train5 = pd.concat([X_train5, y_train5], axis=1)
df_train_hold5 = df_train5[(df_train3['decision']==0)] 
df_train_buy5 = df_train5[(df_train3['decision']==-1)] 
df_train_sell5 = df_train5[(df_train3['decision']==1)] 

# upsample buy and sell class
df_train_buy_upsampled5 = resample(df_train_buy5, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold5)) # to match majority class

df_train_sell_upsampled5 = resample(df_train_sell5, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold5)) # to match majority class

# Combine majority class with upsampled minority classes
df_train_upsampled5 = pd.concat([df_train_buy_upsampled5, df_train_sell_upsampled5, df_train_hold5])
X_train_upsampled5, y_train_upsampled5 = df_train_upsampled5.drop(columns=['decision']), df_train_upsampled5['decision']
y_train_upsampled5.value_counts()

 0    3003
 1     562
-1     227
Name: decision, dtype: int64

# SMOTE RESAMPLE

In [85]:
X_train3[X_train3.isnull().any(axis=1)]

Empty DataFrame
Columns: [adj_close, reddit_pos_both, reddit_neg_both, reddit_neu_both, nyt_pos, nyt_neg, nyt_neu, quarterly_gdp_actual, monthly_cpi_actual, monthly_st_ir_actual, monthly_unemployment_actual]
Index: []

In [86]:
sm3 = SMOTE(sampling_strategy='not majority')
X_train_oversampled3, y_train_oversampled3 = sm3.fit_resample(X_train3, y_train3)
y_train_oversampled3.value_counts()

decision
-1          1264
 0          1264
 1          1264
dtype: int64

In [87]:
sm5 = SMOTE(sampling_strategy='not majority')
X_train_oversampled5, y_train_oversampled5 = sm5.fit_resample(X_train5, y_train5)
y_train_oversampled5.value_counts()

decision
-1          1436
 0          1436
 1          1436
dtype: int64

In [88]:
import sklearn
assert sklearn.__version__ >= "0.20"

np.random.seed(42)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# Random Forest Classifier

In [89]:
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, random_state=42)

## 3% Target Threshold

In [90]:
rnd_clf.fit(X_train3, y_train3)

C:\Users\chloe\AppData\Local\Temp\ipykernel_31588\2543078807.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rnd_clf.fit(X_train3, y_train3)


RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, random_state=42)

### Predicting on train set (3%)

In [91]:
y_predict_train3 = rnd_clf.predict(X_train3)
confusion_matrix_train3 = confusion_matrix(y_train3, y_predict_train3)
accuracy_score_train3 = accuracy_score(y_train3, y_predict_train3)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3))

Confusion_Matrix:
[[   9  138    0]
 [   1 1260    3]
 [   0   70   30]]
Accuracy_Score: 0.8596955658504302



In [92]:
diagonals_train3 = confusion_matrix_train3.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_train3))

Number of Rows Prediction Correctly: 1299



In [93]:
precision_train3 = precision_score(y_train3, y_predict_train3, average = "weighted")
precision_train3

0.8657271496106417

In [94]:
recall_train3 = recall_score(y_train3, y_predict_train3, average = "weighted")
recall_train3 

0.8596955658504302

### Predicting on test set (3%)

In [95]:
y_predict_test3 = rnd_clf.predict(X_test3)
confusion_matrix_test3 = confusion_matrix(y_test3, y_predict_test3)
accuracy_score_test3 = accuracy_score(y_test3, y_predict_test3)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3))

Confusion_Matrix:
[[ 0 39  0]
 [ 0 86  0]
 [ 0 43  0]]
Accuracy_Score: 0.5119047619047619



In [96]:
diagonals_test3 = confusion_matrix_test3.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3))

Number of Rows Prediction Correctly: 86



In [97]:
precision_test3 = precision_score(y_test3, y_predict_test3, average = "weighted")
precision_test3

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.26204648526077096

In [98]:
recall_test3 = recall_score(y_test3, y_predict_test3, average = "weighted")
recall_test3 

0.5119047619047619

## SKLearn Resample 3% 

In [99]:
rnd_clf.fit(X_train_upsampled3, y_train_upsampled3)

RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, random_state=42)

### [SKLEARN RESAMPLE] Predicting on train set (3%)

In [100]:
y_predict_train3sk = rnd_clf.predict(X_train_upsampled3)
confusion_matrix_train3sk = confusion_matrix(y_train_upsampled3, y_predict_train3sk)
accuracy_score_train3sk = accuracy_score(y_train_upsampled3, y_predict_train3sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3sk))

Confusion_Matrix:
[[ 947  242   75]
 [ 238  877  149]
 [ 101   28 1135]]
Accuracy_Score: 0.7803270042194093



In [101]:
skdiagonals_train3sk = confusion_matrix_train3sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train3sk))

Number of Rows Prediction Correctly: 2959



In [102]:
precision_train3sk = precision_score(y_train_upsampled3, y_predict_train3sk, average = "weighted")
precision_train3sk

0.7787227157214296

In [103]:
recall_train3sk = recall_score(y_train_upsampled3, y_predict_train3sk, average = "weighted")
recall_train3sk

0.7803270042194093

### [SKLEARN RESAMPLE] Predicting on test set (3%)

In [104]:
y_predict_test3sk = rnd_clf.predict(X_test3)
confusion_matrix_test3sk = confusion_matrix(y_test3, y_predict_test3sk)
accuracy_score_test3sk = accuracy_score(y_test3, y_predict_test3sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3sk))

Confusion_Matrix:
[[ 9 25  5]
 [12 58 16]
 [ 9 22 12]]
Accuracy_Score: 0.47023809523809523



In [105]:
diagonals_test3sk = confusion_matrix_test3sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3sk))

Number of Rows Prediction Correctly: 79



In [106]:
precision_test3sk = precision_score(y_test3, y_predict_test3sk, average = "weighted")
precision_test3sk 

0.4454828901257473

In [107]:
recall_test3sk = recall_score(y_test3, y_predict_test3sk, average = "weighted")
recall_test3sk 

0.47023809523809523

## SMOTE Resample 3% 

In [108]:
rnd_clf.fit(X_train_oversampled3, y_train_oversampled3)

C:\Users\chloe\AppData\Local\Temp\ipykernel_31588\2267759465.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rnd_clf.fit(X_train_oversampled3, y_train_oversampled3)


RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, random_state=42)

### [SMOTE] Predicting on train set (3%)

In [109]:
y_predict_train3sm = rnd_clf.predict(X_train_oversampled3)
confusion_matrix_train3sm = confusion_matrix(y_train_oversampled3, y_predict_train3sm)
accuracy_score_train3sm = accuracy_score(y_train_oversampled3, y_predict_train3sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3sm))

Confusion_Matrix:
[[ 909  283   72]
 [ 218  901  145]
 [  57   54 1153]]
Accuracy_Score: 0.7813818565400844



In [110]:
skdiagonals_train3sm = confusion_matrix_train3sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train3sm))

Number of Rows Prediction Correctly: 2963



In [111]:
precision_train3sm = precision_score(y_train_oversampled3, y_predict_train3sm, average = "weighted")
precision_train3sm

0.7790430262432285

In [112]:
recall_train3sm = recall_score(y_train_oversampled3, y_predict_train3sm, average = "weighted")
recall_train3sm

0.7813818565400844

### [SMOTE] Predicting on test set (3%)

In [113]:
y_predict_test3sm = rnd_clf.predict(X_test3)
confusion_matrix_test3sm = confusion_matrix(y_test3, y_predict_test3sm)
accuracy_score_test3sm = accuracy_score(y_test3, y_predict_test3sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3sm))

Confusion_Matrix:
[[ 5 28  6]
 [ 4 66 16]
 [ 5 25 13]]
Accuracy_Score: 0.5



In [114]:
diagonals_test3sm = confusion_matrix_test3sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3sm))

Number of Rows Prediction Correctly: 84



In [115]:
precision_test3sm = precision_score(y_test3, y_predict_test3sm, average = "weighted")
precision_test3sm

0.461889755902361

In [116]:
recall_test3sm= recall_score(y_test3, y_predict_test3sm, average = "weighted")
recall_test3sm

0.5

## 5% Target threshold

In [117]:
rnd_clf.fit(X_train5, y_train5)

C:\Users\chloe\AppData\Local\Temp\ipykernel_31588\2076458165.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rnd_clf.fit(X_train5, y_train5)


RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, random_state=42)

### Predicting on train set (5%)

In [118]:
y_predict_train5 = rnd_clf.predict(X_train5)
confusion_matrix_train5 = confusion_matrix(y_train5, y_predict_train5)
accuracy_score_train5 = accuracy_score(y_train5, y_predict_train5)
print("Confusion_Matrix (5%):\n{}"
      .format(confusion_matrix_train5))
print("Accuracy_Score (5%): {}\n"
      .format(accuracy_score_train5))

Confusion_Matrix (5%):
[[   8   22    0]
 [   0 1435    1]
 [   0   27   18]]
Accuracy_Score (5%): 0.9669093315684977



In [119]:
diagonals_train5 = confusion_matrix_train5.diagonal().sum()
print("Number of Rows Prediction Correctly (5%): {}\n"
      .format(diagonals_train5))

Number of Rows Prediction Correctly (5%): 1461



In [120]:
TP_train5 = confusion_matrix_train5[1, 1]
TN_train5 = confusion_matrix_train5[0, 0]
FP_train5 = confusion_matrix_train5[0, 1]
FN_train5 = confusion_matrix_train5[1, 0]

In [121]:
precision_train5 = precision_score(y_train5, y_predict_train5, average = "weighted")
precision_train5

0.9670526039760063

In [122]:
recall_train5 = recall_score(y_train5, y_predict_train5, average = "weighted")
recall_train5

0.9669093315684977

### Predicting on test set (5%)

In [123]:
y_predict_test5 = rnd_clf.predict(X_test5)
confusion_matrix_test5 = confusion_matrix(y_test5, y_predict_test5)
accuracy_score_test5 = accuracy_score(y_test5, y_predict_test5)
print("Confusion_Matrix (5%):\n{}"
      .format(confusion_matrix_test5))
print("Accuracy_Score (5%): {}\n"
      .format(accuracy_score_test5))

Confusion_Matrix (5%):
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score (5%): 0.8154761904761905



In [124]:
diagonals_test5 = confusion_matrix_test5.diagonal().sum()
print("Number of Rows Prediction Correctly (5%): {}\n"
      .format(diagonals_test5))

Number of Rows Prediction Correctly (5%): 137



In [125]:
precision_test5 = precision_score(y_test5, y_predict_test5, average = "weighted")
precision_test5 

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6650014172335601

In [126]:
recall_test5 = recall_score(y_test5, y_predict_test5, average = "weighted")
recall_test5 

0.8154761904761905

## SKLearn Resample 5% 

In [127]:
rnd_clf.fit(X_train_upsampled5, y_train_upsampled5)

RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, random_state=42)

### [SKLEARN RESAMPLE] Predicting on train set (5%)

In [128]:
y_predict_train5sk = rnd_clf.predict(X_train_upsampled5)
confusion_matrix_train5sk = confusion_matrix(y_train_upsampled5, y_predict_train5sk)
accuracy_score_train5sk = accuracy_score(y_train_upsampled5, y_predict_train5sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train5sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train5sk))

Confusion_Matrix:
[[  60  162    5]
 [   1 2981   21]
 [   0  171  391]]
Accuracy_Score: 0.9050632911392406



In [129]:
skdiagonals_train5sk = confusion_matrix_train5sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train5sk))

Number of Rows Prediction Correctly: 3432



In [130]:
precision_train5sk = precision_score(y_train_upsampled5, y_predict_train5sk, average = "weighted")
precision_train5sk

0.9102025506364911

In [131]:
recall_train5sk = recall_score(y_train_upsampled5, y_predict_train5sk, average = "weighted")
recall_train5sk

0.9050632911392406

### [SKLEARN RESAMPLE] Predicting on test set (5%)

In [132]:
y_predict_test5sk = rnd_clf.predict(X_test5)
confusion_matrix_test5sk = confusion_matrix(y_test5, y_predict_test5sk)
accuracy_score_test5sk = accuracy_score(y_test5, y_predict_test5sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test5sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test5sk))

Confusion_Matrix:
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score: 0.8154761904761905



In [133]:
diagonals_test5sk = confusion_matrix_test5sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test5sk))

Number of Rows Prediction Correctly: 137



In [134]:
precision_test5sk = precision_score(y_test5, y_predict_test5sk, average = "weighted")
precision_test5sk 

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6650014172335601

In [135]:
recall_test5sk = recall_score(y_test5, y_predict_test5sk, average = "weighted")
recall_test5sk 

0.8154761904761905

## SMOTE Resample 5% 

In [136]:
rnd_clf.fit(X_train_oversampled5, y_train_oversampled5)

C:\Users\chloe\AppData\Local\Temp\ipykernel_31588\2570895408.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rnd_clf.fit(X_train_oversampled5, y_train_oversampled5)


RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, random_state=42)

### [SMOTE] Predicting on train set (5%)

In [137]:
y_predict_train5sm = rnd_clf.predict(X_train_oversampled5)
confusion_matrix_train5sm = confusion_matrix(y_train_oversampled5, y_predict_train5sm)
accuracy_score_train5sm = accuracy_score(y_train_oversampled5, y_predict_train5sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train5sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train5sm))

Confusion_Matrix:
[[1249  136   51]
 [  79 1263   94]
 [  16   36 1384]]
Accuracy_Score: 0.904363974001857



In [138]:
skdiagonals_train5sm = confusion_matrix_train5sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train5sm))

Number of Rows Prediction Correctly: 3896



In [139]:
precision_train5sm = precision_score(y_train_oversampled5, y_predict_train5sm, average = "weighted")
precision_train5sm

0.904873874894383

In [140]:
recall_train5sm = recall_score(y_train_oversampled5, y_predict_train5sm, average = "weighted")
recall_train5sm

0.904363974001857

### [SMOTE] Predicting on test set (5%)

In [141]:
y_predict_test5sm = rnd_clf.predict(X_test5)
confusion_matrix_test5sm = confusion_matrix(y_test5, y_predict_test5sm)
accuracy_score_test5sm = accuracy_score(y_test5, y_predict_test5sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test5sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test5sm))

Confusion_Matrix:
[[  0   9   1]
 [  0 134   3]
 [  0  19   2]]
Accuracy_Score: 0.8095238095238095



In [142]:
diagonals_test5sm = confusion_matrix_test5sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test5sm))

Number of Rows Prediction Correctly: 136



In [143]:
precision_test5sm = precision_score(y_test5, y_predict_test5sm, average = "weighted")
precision_test5sm

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.7161963550852439

In [144]:
recall_test5sm= recall_score(y_test5, y_predict_test5sm, average = "weighted")
recall_test5sm

0.8095238095238095

In [146]:
dfrf = pd.DataFrame({
    'model': ['RF 3%', 'RF 3% SK Resample', 'RF 3% SMOTE', 'RF 5%', 'RF 5% SK Resample', 'RF 5% SMOTE',],
    'accuracy': [accuracy_score_test3,accuracy_score_test3sk, accuracy_score_test3sm, accuracy_score_test5,accuracy_score_test5sk, accuracy_score_test5sm],
    'recall': [recall_test3, recall_test3sk, recall_test3sm, recall_test5, recall_test5sk, recall_test5sm],
    'precision': [precision_test3, precision_test3sk, precision_test3sm, precision_test5, precision_test5sk, precision_test5sm],
})

dfrf

model  accuracy    recall  precision
0              RF 3%  0.511905  0.511905   0.262046
1  RF 3% SK Resample  0.470238  0.470238   0.445483
2        RF 3% SMOTE  0.500000  0.500000   0.461890
3              RF 5%  0.815476  0.815476   0.665001
4  RF 5% SK Resample  0.815476  0.815476   0.665001
5        RF 5% SMOTE  0.809524  0.809524   0.716196