In [431]:
import pandas as pd 
import numpy as np

In [432]:
X_train3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_train3.xlsx")
y_train3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_train3.xlsx")

X_test3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_test3.xlsx")
y_test3 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_test3.xlsx")

In [433]:
X_train5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_train5.xlsx")
y_train5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_train5.xlsx")

X_test5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_test5.xlsx")
y_test5 = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_test5.xlsx")

In [434]:
X_train3 = X_train3.iloc[: , 1:]
y_train3 = y_train3.iloc[: , 1:]

X_test3 = X_test3.iloc[: , 1:]
y_test3 = y_test3.iloc[: , 1:]

In [435]:
X_train5 = X_train5.iloc[: , 1:]
y_train5 = y_train5.iloc[: , 1:]

X_test5 = X_test5.iloc[: , 1:]
y_test5 = y_test5.iloc[: , 1:]

In [436]:
import sklearn
assert sklearn.__version__ >= "0.20"

from sklearn.svm import SVC
from sklearn import svm
from sklearn.svm import LinearSVC 
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE

# SKLEARN RESAMPLE

In [437]:
df_train3 = pd.concat([X_train3, y_train3], axis=1)
df_train_hold3 = df_train3[(df_train3['decision']==0)] 
df_train_buy3 = df_train3[(df_train3['decision']==-1)] 
df_train_sell3 = df_train3[(df_train3['decision']==1)] 

# upsample buy and sell class
df_train_buy_upsampled3 = resample(df_train_buy3, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold3)) # to match majority class

df_train_sell_upsampled3 = resample(df_train_sell3, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold3)) # to match majority class

# Combine majority class with upsampled minority classes
df_train_upsampled3 = pd.concat([df_train_buy_upsampled3, df_train_sell_upsampled3, df_train_hold3])
X_train_upsampled3, y_train_upsampled3 = df_train_upsampled3.drop(columns=['decision']), df_train_upsampled3['decision']
y_train_upsampled3.value_counts()

 0    1264
-1    1264
 1    1264
Name: decision, dtype: int64

In [438]:
df_train5 = pd.concat([X_train5, y_train5], axis=1)
df_train_hold5 = df_train5[(df_train3['decision']==0)] 
df_train_buy5 = df_train5[(df_train3['decision']==-1)] 
df_train_sell5 = df_train5[(df_train3['decision']==1)] 

# upsample buy and sell class
df_train_buy_upsampled5 = resample(df_train_buy5, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold5)) # to match majority class

df_train_sell_upsampled5 = resample(df_train_sell5, 
                                 replace=True,    # sample with replacement
                                 n_samples= len(df_train_hold5)) # to match majority class

# Combine majority class with upsampled minority classes
df_train_upsampled5 = pd.concat([df_train_buy_upsampled5, df_train_sell_upsampled5, df_train_hold5])
X_train_upsampled5, y_train_upsampled5 = df_train_upsampled5.drop(columns=['decision']), df_train_upsampled5['decision']
y_train_upsampled5.value_counts()

 0    2943
 1     581
-1     268
Name: decision, dtype: int64

# SMOTE RESAMPLE

In [439]:
X_train3[X_train3.isnull().any(axis=1)]

Empty DataFrame
Columns: [adj_close, reddit_pos_both, reddit_neg_both, reddit_neu_both, nyt_pos, nyt_neg, nyt_neu, quarterly_gdp_actual, monthly_cpi_actual, monthly_st_ir_actual, monthly_unemployment_actual]
Index: []

In [440]:
sm3 = SMOTE(sampling_strategy='not majority')
X_train_oversampled3, y_train_oversampled3 = sm3.fit_resample(X_train3, y_train3)
y_train_oversampled3.value_counts()

decision
-1          1264
 0          1264
 1          1264
dtype: int64

In [441]:
sm5 = SMOTE(sampling_strategy='not majority')
X_train_oversampled5, y_train_oversampled5 = sm5.fit_resample(X_train5, y_train5)
y_train_oversampled5.value_counts()

decision
-1          1436
 0          1436
 1          1436
dtype: int64

 # Linear SVM


In [442]:
linearsvc = LinearSVC(C=1, loss="hinge", random_state=42)

## 3% Target Threshold

In [443]:
linearsvc.fit(X_train3, y_train3)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(C=1, loss='hinge', random_state=42)

### Predicting on train set (3%)

In [444]:
y_predict_train3 = linearsvc.predict(X_train3)
confusion_matrix_train3 = confusion_matrix(y_train3, y_predict_train3)
accuracy_score_train3 = accuracy_score(y_train3, y_predict_train3)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3))

Confusion_Matrix:
[[   0  147    0]
 [   0 1264    0]
 [   0  100    0]]
Accuracy_Score: 0.8365320979483786



In [445]:
diagonals_train3 = confusion_matrix_train3.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_train3))

Number of Rows Prediction Correctly: 1264



In [446]:
precision_train3 = precision_score(y_train3, y_predict_train3, average = "weighted")
precision_train3

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6997859508979156

In [447]:
recall_train3 = recall_score(y_train3, y_predict_train3, average = "weighted")
recall_train3 

0.8365320979483786

### Predicting on test set (3%)

In [448]:
y_predict_test3 = linearsvc.predict(X_test3)
confusion_matrix_test3 = confusion_matrix(y_test3, y_predict_test3)
accuracy_score_test3 = accuracy_score(y_test3, y_predict_test3)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3))

Confusion_Matrix:
[[ 0 39  0]
 [ 0 86  0]
 [ 0 43  0]]
Accuracy_Score: 0.5119047619047619



In [449]:
diagonals_test3 = confusion_matrix_test3.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3))

Number of Rows Prediction Correctly: 86



In [450]:
precision_test3 = precision_score(y_test3, y_predict_test3, average = "weighted")
precision_test3

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.26204648526077096

In [451]:
recall_test3 = recall_score(y_test3, y_predict_test3, average = "weighted")
recall_test3 

0.5119047619047619

## SKLearn Resample 3% 

In [452]:
linearsvc.fit(X_train_upsampled3, y_train_upsampled3)

C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(C=1, loss='hinge', random_state=42)

### [SKLEARN RESAMPLE] Predicting on train set (3%)

In [453]:
y_predict_train3sk = linearsvc.predict(X_train_upsampled3)
confusion_matrix_train3sk = confusion_matrix(y_train_upsampled3, y_predict_train3sk)
accuracy_score_train3sk = accuracy_score(y_train_upsampled3, y_predict_train3sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3sk))

Confusion_Matrix:
[[ 891  124  249]
 [ 683  131  450]
 [ 201   62 1001]]
Accuracy_Score: 0.5334915611814346



In [454]:
skdiagonals_train3sk = confusion_matrix_train3sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train3sk))

Number of Rows Prediction Correctly: 2023



In [455]:
precision_train3sk = precision_score(y_train_upsampled3, y_predict_train3sk, average = "weighted")
precision_train3sk

0.5013481905847158

In [456]:
recall_train3sk = recall_score(y_train_upsampled3, y_predict_train3sk, average = "weighted")
recall_train3sk

0.5334915611814346

### [SKLEARN RESAMPLE] Predicting on test set (3%)

In [457]:
y_predict_test3sk = linearsvc.predict(X_test3)
confusion_matrix_test3sk = confusion_matrix(y_test3, y_predict_test3sk)
accuracy_score_test3sk = accuracy_score(y_test3, y_predict_test3sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3sk))

Confusion_Matrix:
[[10  8 21]
 [13  7 66]
 [ 0  2 41]]
Accuracy_Score: 0.34523809523809523



In [458]:
diagonals_test3sk = confusion_matrix_test3sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3sk))

Number of Rows Prediction Correctly: 58



In [459]:
precision_test3sk = precision_score(y_test3, y_predict_test3sk, average = "weighted")
precision_test3sk 

0.39370073776793324

In [460]:
recall_test3sk = recall_score(y_test3, y_predict_test3sk, average = "weighted")
recall_test3sk 

0.34523809523809523

## SMOTE Resample 3% 

In [461]:
linearsvc.fit(X_train_oversampled3, y_train_oversampled3)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(C=1, loss='hinge', random_state=42)

### [SMOTE] Predicting on train set (3%)

In [462]:
y_predict_train3sm = linearsvc.predict(X_train_oversampled3)
confusion_matrix_train3sm = confusion_matrix(y_train_oversampled3, y_predict_train3sm)
accuracy_score_train3sm = accuracy_score(y_train_oversampled3, y_predict_train3sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3sm))

Confusion_Matrix:
[[885 125 254]
 [653 161 450]
 [221  59 984]]
Accuracy_Score: 0.5353375527426161



In [463]:
skdiagonals_train3sm = confusion_matrix_train3sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train3sm))

Number of Rows Prediction Correctly: 2030



In [464]:
precision_train3sm = precision_score(y_train_oversampled3, y_predict_train3sm, average = "weighted")
precision_train3sm

0.5175772772899534

In [465]:
recall_train3sm = recall_score(y_train_oversampled3, y_predict_train3sm, average = "weighted")
recall_train3sm

0.5353375527426161

### [SMOTE] Predicting on test set (3%)

In [466]:
y_predict_test3sm = linearsvc.predict(X_test3)
confusion_matrix_test3sm = confusion_matrix(y_test3, y_predict_test3sm)
accuracy_score_test3sm = accuracy_score(y_test3, y_predict_test3sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3sm))

Confusion_Matrix:
[[10  9 20]
 [13  8 65]
 [ 1  2 40]]
Accuracy_Score: 0.34523809523809523



In [467]:
diagonals_test3sm = confusion_matrix_test3sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3sm))

Number of Rows Prediction Correctly: 58



In [468]:
precision_test3sm = precision_score(y_test3, y_predict_test3sm, average = "weighted")
precision_test3sm

0.39416979949874686

In [469]:
recall_test3sm= recall_score(y_test3, y_predict_test3sm, average = "weighted")
recall_test3sm

0.34523809523809523

## 5% Target threshold

In [470]:
linearsvc.fit(X_train5, y_train5)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(C=1, loss='hinge', random_state=42)

### Predicting on train set (5%)

In [471]:
y_predict_train5 = linearsvc.predict(X_train5)
confusion_matrix_train5 = confusion_matrix(y_train5, y_predict_train5)
accuracy_score_train5 = accuracy_score(y_train5, y_predict_train5)
print("Confusion_Matrix (5%):\n{}"
      .format(confusion_matrix_train5))
print("Accuracy_Score (5%): {}\n"
      .format(accuracy_score_train5))

Confusion_Matrix (5%):
[[   0   30    0]
 [   0 1436    0]
 [   0   45    0]]
Accuracy_Score (5%): 0.9503639973527466



In [472]:
diagonals_train5 = confusion_matrix_train5.diagonal().sum()
print("Number of Rows Prediction Correctly (5%): {}\n"
      .format(diagonals_train5))

Number of Rows Prediction Correctly (5%): 1436



In [473]:
TP_train5 = confusion_matrix_train5[1, 1]
TN_train5 = confusion_matrix_train5[0, 0]
FP_train5 = confusion_matrix_train5[0, 1]
FN_train5 = confusion_matrix_train5[1, 0]

In [474]:
precision_train5 = precision_score(y_train5, y_predict_train5, average = "weighted")
precision_train5

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.9031917274642912

In [475]:
recall_train5 = recall_score(y_train5, y_predict_train5, average = "weighted")
recall_train5

0.9503639973527466

### Predicting on test set (5%)

In [476]:
y_predict_test5 = linearsvc.predict(X_test5)
confusion_matrix_test5 = confusion_matrix(y_test5, y_predict_test5)
accuracy_score_test5 = accuracy_score(y_test5, y_predict_test5)
print("Confusion_Matrix (5%):\n{}"
      .format(confusion_matrix_test5))
print("Accuracy_Score (5%): {}\n"
      .format(accuracy_score_test5))

Confusion_Matrix (5%):
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score (5%): 0.8154761904761905



In [477]:
diagonals_test5 = confusion_matrix_test5.diagonal().sum()
print("Number of Rows Prediction Correctly (5%): {}\n"
      .format(diagonals_test5))

Number of Rows Prediction Correctly (5%): 137



In [478]:
precision_test5 = precision_score(y_test5, y_predict_test5, average = "weighted")
precision_test5 

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6650014172335601

In [479]:
recall_test5 = recall_score(y_test5, y_predict_test5, average = "weighted")
recall_test5 

0.8154761904761905

## SKLearn Resample 5% 

In [480]:
linearsvc.fit(X_train_upsampled5, y_train_upsampled5)

C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(C=1, loss='hinge', random_state=42)

### [SKLEARN RESAMPLE] Predicting on train set (5%)

In [481]:
y_predict_train5sk = linearsvc.predict(X_train_upsampled5)
confusion_matrix_train5sk = confusion_matrix(y_train_upsampled5, y_predict_train5sk)
accuracy_score_train5sk = accuracy_score(y_train_upsampled5, y_predict_train5sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train5sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train5sk))

Confusion_Matrix:
[[   0  257   11]
 [   0 2828  115]
 [   0  289  292]]
Accuracy_Score: 0.8227848101265823



In [482]:
skdiagonals_train5sk = confusion_matrix_train5sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train5sk))

Number of Rows Prediction Correctly: 3120



In [483]:
precision_train5sk = precision_score(y_train_upsampled5, y_predict_train5sk, average = "weighted")
precision_train5sk

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.7575456003889607

In [484]:
recall_train5sk = recall_score(y_train_upsampled5, y_predict_train5sk, average = "weighted")
recall_train5sk

0.8227848101265823

### [SKLEARN RESAMPLE] Predicting on test set (5%)

In [485]:
y_predict_test5sk = linearsvc.predict(X_test5)
confusion_matrix_test5sk = confusion_matrix(y_test5, y_predict_test5sk)
accuracy_score_test5sk = accuracy_score(y_test5, y_predict_test5sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test5sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test5sk))

Confusion_Matrix:
[[  0  10   0]
 [  0 134   3]
 [  0  20   1]]
Accuracy_Score: 0.8035714285714286



In [486]:
diagonals_test5sk = confusion_matrix_test5sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test5sk))

Number of Rows Prediction Correctly: 135



In [487]:
precision_test5sk = precision_score(y_test5, y_predict_test5sk, average = "weighted")
precision_test5sk 

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6975537166085947

In [488]:
recall_test5sk = recall_score(y_test5, y_predict_test5sk, average = "weighted")
recall_test5sk 

0.8035714285714286

## SMOTE Resample 5% 

In [489]:
linearsvc.fit(X_train_oversampled5, y_train_oversampled5)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(C=1, loss='hinge', random_state=42)

### [SMOTE] Predicting on train set (5%)

In [490]:
y_predict_train5sm = linearsvc.predict(X_train_oversampled5)
confusion_matrix_train5sm = confusion_matrix(y_train_oversampled5, y_predict_train5sm)
accuracy_score_train5sm = accuracy_score(y_train_oversampled5, y_predict_train5sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train5sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train5sm))

Confusion_Matrix:
[[1153  217   66]
 [ 204 1019  213]
 [  40   70 1326]]
Accuracy_Score: 0.8119777158774373



In [491]:
skdiagonals_train5sm = confusion_matrix_train5sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train5sm))

Number of Rows Prediction Correctly: 3498



In [492]:
precision_train5sm = precision_score(y_train_oversampled5, y_predict_train5sm, average = "weighted")
precision_train5sm

0.8105844205287871

In [493]:
recall_train5sm = recall_score(y_train_oversampled5, y_predict_train5sm, average = "weighted")
recall_train5sm

0.8119777158774373

### [SMOTE] Predicting on test set (5%)

In [494]:
y_predict_test5sm = linearsvc.predict(X_test5)
confusion_matrix_test5sm = confusion_matrix(y_test5, y_predict_test5sm)
accuracy_score_test5sm = accuracy_score(y_test5, y_predict_test5sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test5sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test5sm))

Confusion_Matrix:
[[  0  10   0]
 [ 11 120   6]
 [  0  17   4]]
Accuracy_Score: 0.7380952380952381



In [495]:
diagonals_test5sm = confusion_matrix_test5sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test5sm))

Number of Rows Prediction Correctly: 124



In [496]:
precision_test5sm = precision_score(y_test5, y_predict_test5sm, average = "weighted")
precision_test5sm

0.7156948493683188

In [497]:
recall_test5sm= recall_score(y_test5, y_predict_test5sm, average = "weighted")
recall_test5sm

0.7380952380952381

In [498]:
dflinear = pd.DataFrame({
    'model': ['Linear SVC 3%', 'Linear SVC 3% SK Resample', 'Linear SVC 3% SMOTE', 'Linear SVC 5%', 'Linear SVC 5% SK Resample', 'Linear SVC 5% SMOTE',],
    'accuracy': [accuracy_score_test3,accuracy_score_test3sk, accuracy_score_test3sm, accuracy_score_test5,accuracy_score_test5sk, accuracy_score_test5sm],
    'recall': [recall_test3, recall_test3sk, recall_test3sm, recall_test5, recall_test5sk, recall_test5sm],
    'precision': [precision_test3, precision_test3sk, precision_test3sm, precision_test5, precision_test5sk, precision_test5sm],
})

dflinear 

model  accuracy    recall  precision
0              Linear SVC 3%  0.511905  0.511905   0.262046
1  Linear SVC 3% SK Resample  0.345238  0.345238   0.393701
2        Linear SVC 3% SMOTE  0.345238  0.345238   0.394170
3              Linear SVC 5%  0.815476  0.815476   0.665001
4  Linear SVC 5% SK Resample  0.803571  0.803571   0.697554
5        Linear SVC 5% SMOTE  0.738095  0.738095   0.715695

# RBF SVM

In [499]:
rbf_svc = svm.SVC(kernel='rbf', gamma = "scale")

## 3% Target Threshold

In [500]:
rbf_svc.fit(X_train3, y_train3)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

### Predicting on train set (3%)

In [501]:
y_predict_train3 = rbf_svc.predict(X_train3)
confusion_matrix_train3 = confusion_matrix(y_train3, y_predict_train3)
accuracy_score_train3 = accuracy_score(y_train3, y_predict_train3)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3))

Confusion_Matrix:
[[   9  136    2]
 [   1 1261    2]
 [   0   77   23]]
Accuracy_Score: 0.8557246856386499



In [502]:
diagonals_train3 = confusion_matrix_train3.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_train3))

Number of Rows Prediction Correctly: 1293



In [503]:
precision_train3 = precision_score(y_train3, y_predict_train3, average = "weighted")
precision_train3

0.8595838401531972

In [504]:
recall_train3 = recall_score(y_train3, y_predict_train3, average = "weighted")
recall_train3 

0.8557246856386499

### Predicting on test set (3%)

In [505]:
y_predict_test3 = rbf_svc.predict(X_test3)
confusion_matrix_test3 = confusion_matrix(y_test3, y_predict_test3)
accuracy_score_test3 = accuracy_score(y_test3, y_predict_test3)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3))

Confusion_Matrix:
[[ 0 39  0]
 [ 0 86  0]
 [ 0 43  0]]
Accuracy_Score: 0.5119047619047619



In [506]:
diagonals_test3 = confusion_matrix_test3.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3))

Number of Rows Prediction Correctly: 86



In [507]:
precision_test = precision_score(y_test3, y_predict_test3, average = "weighted")
precision_test 

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.26204648526077096

In [508]:
recall_test = recall_score(y_test3, y_predict_test3, average = "weighted")
recall_test 

0.5119047619047619

## SKLearn Resample 3% 

In [509]:
rbf_svc.fit(X_train_upsampled3, y_train_upsampled3)

SVC()

### [SKLEARN RESAMPLE] Predicting on train set (3%)

In [510]:
y_predict_train3sk = rbf_svc.predict(X_train_upsampled3)
confusion_matrix_train3sk = confusion_matrix(y_train_upsampled3, y_predict_train3sk)
accuracy_score_train3sk = accuracy_score(y_train_upsampled3, y_predict_train3sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3sk))

Confusion_Matrix:
[[1062  157   45]
 [ 208  918  138]
 [  62   24 1178]]
Accuracy_Score: 0.8328059071729957



In [511]:
skdiagonals_train3sk = confusion_matrix_train3sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train3sk))

Number of Rows Prediction Correctly: 3158



In [512]:
precision_train3sk = precision_score(y_train_upsampled3, y_predict_train3sk, average = "weighted")
precision_train3sk

0.8327140546494992

In [513]:
recall_train3sk = recall_score(y_train_upsampled3, y_predict_train3sk, average = "weighted")
recall_train3sk

0.8328059071729957

### [SKLEARN RESAMPLE] Predicting on test set (3%)

In [514]:
y_predict_test3sk = rbf_svc.predict(X_test3)
confusion_matrix_test3sk = confusion_matrix(y_test3, y_predict_test3sk)
accuracy_score_test3sk = accuracy_score(y_test3, y_predict_test3sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3sk))

Confusion_Matrix:
[[ 9 26  4]
 [ 4 67 15]
 [ 3 33  7]]
Accuracy_Score: 0.49404761904761907



In [515]:
diagonals_test3sk = confusion_matrix_test3sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3sk))

Number of Rows Prediction Correctly: 83



In [516]:
precision_test3sk = precision_score(y_test3, y_predict_test3sk, average = "weighted")
precision_test3sk 

0.47169393932786796

In [517]:
recall_test3sk = recall_score(y_test3, y_predict_test3sk, average = "weighted")
recall_test3sk 

0.49404761904761907

## SMOTE Resample 3% 

In [518]:
rbf_svc.fit(X_train_oversampled3, y_train_oversampled3)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

### [SMOTE] Predicting on train set (3%)

In [519]:
y_predict_train3sm = rbf_svc.predict(X_train_oversampled3)
confusion_matrix_train3sm = confusion_matrix(y_train_oversampled3, y_predict_train3sm)
accuracy_score_train3sm = accuracy_score(y_train_oversampled3, y_predict_train3sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train3sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train3sm))

Confusion_Matrix:
[[1054  166   44]
 [ 201  948  115]
 [  57   17 1190]]
Accuracy_Score: 0.8417721518987342



In [520]:
skdiagonals_train3sm = confusion_matrix_train3sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train3sm))

Number of Rows Prediction Correctly: 3192



In [521]:
precision_train3sm = precision_score(y_train_oversampled3, y_predict_train3sm, average = "weighted")
precision_train3sm

0.8412282865868005

In [522]:
recall_train3sm = recall_score(y_train_oversampled3, y_predict_train3sm, average = "weighted")
recall_train3sm

0.8417721518987342

### [SMOTE] Predicting on test set (3%)

In [523]:
y_predict_test3sm = rbf_svc.predict(X_test3)
confusion_matrix_test3sm = confusion_matrix(y_test3, y_predict_test3sm)
accuracy_score_test3sm = accuracy_score(y_test3, y_predict_test3sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test3sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test3sm))

Confusion_Matrix:
[[ 2 37  0]
 [ 5 77  4]
 [ 0 41  2]]
Accuracy_Score: 0.48214285714285715



In [524]:
diagonals_test3sm = confusion_matrix_test3sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test3sm))

Number of Rows Prediction Correctly: 81



In [525]:
precision_test3sm = precision_score(y_test3, y_predict_test3sm, average = "weighted")
precision_test3sm

0.40594506619852233

In [526]:
recall_test3sm= recall_score(y_test3, y_predict_test3sm, average = "weighted")
recall_test3sm

0.48214285714285715

## 5% Target threshold

In [527]:
rbf_svc.fit(X_train5, y_train5)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

### Predicting on train set (5%)

In [528]:
y_predict_train5 = rbf_svc.predict(X_train5)
confusion_matrix_train5 = confusion_matrix(y_train5, y_predict_train5)
accuracy_score_train5 = accuracy_score(y_train5, y_predict_train5)
print("Confusion_Matrix (5%):\n{}"
      .format(confusion_matrix_train5))
print("Accuracy_Score (5%): {}\n"
      .format(accuracy_score_train5))

Confusion_Matrix (5%):
[[   4   26    0]
 [   0 1433    3]
 [   0   37    8]]
Accuracy_Score (5%): 0.9563203176704169



In [529]:
diagonals_train5 = confusion_matrix_train5.diagonal().sum()
print("Number of Rows Prediction Correctly (5%): {}\n"
      .format(diagonals_train5))

Number of Rows Prediction Correctly (5%): 1445



In [530]:
TP_train5 = confusion_matrix_train5[1, 1]
TN_train5 = confusion_matrix_train5[0, 0]
FP_train5 = confusion_matrix_train5[0, 1]
FN_train5 = confusion_matrix_train5[1, 0]

In [531]:
precision_train5 = precision_score(y_train5, y_predict_train5, average = "weighted")
precision_train5

0.9518557317638565

In [532]:
recall_train5 = recall_score(y_train5, y_predict_train5, average = "weighted")
recall_train5

0.9563203176704169

### Predicting on test set (5%)

In [533]:
y_predict_test5 = rbf_svc.predict(X_test5)
confusion_matrix_test5 = confusion_matrix(y_test5, y_predict_test5)
accuracy_score_test5 = accuracy_score(y_test5, y_predict_test5)
print("Confusion_Matrix (5%):\n{}"
      .format(confusion_matrix_test5))
print("Accuracy_Score (5%): {}\n"
      .format(accuracy_score_test5))

Confusion_Matrix (5%):
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score (5%): 0.8154761904761905



In [534]:
diagonals_test5 = confusion_matrix_test5.diagonal().sum()
print("Number of Rows Prediction Correctly (5%): {}\n"
      .format(diagonals_test5))

Number of Rows Prediction Correctly (5%): 137



In [535]:
precision_test5 = precision_score(y_test5, y_predict_test5, average = "weighted")
precision_test5 

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6650014172335601

In [536]:
recall_test5 = recall_score(y_test5, y_predict_test5, average = "weighted")
recall_test5 

0.8154761904761905

## SKLearn Resample 5% 

In [537]:
rbf_svc.fit(X_train_upsampled5, y_train_upsampled5)

SVC()

### [SKLEARN RESAMPLE] Predicting on train set (5%)

In [538]:
y_predict_train5sk = rbf_svc.predict(X_train_upsampled5)
confusion_matrix_train5sk = confusion_matrix(y_train_upsampled5, y_predict_train5sk)
accuracy_score_train5sk = accuracy_score(y_train_upsampled5, y_predict_train5sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train5sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train5sk))

Confusion_Matrix:
[[ 135  133    0]
 [   4 2896   43]
 [   0  142  439]]
Accuracy_Score: 0.915084388185654



In [539]:
skdiagonals_train5sk = confusion_matrix_train5sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train5sk))

Number of Rows Prediction Correctly: 3470



In [540]:
precision_train5sk = precision_score(y_train_upsampled5, y_predict_train5sk, average = "weighted")
precision_train5sk

0.9169907072431968

In [541]:
recall_train5sk = recall_score(y_train_upsampled5, y_predict_train5sk, average = "weighted")
recall_train5sk

0.915084388185654

### [SKLEARN RESAMPLE] Predicting on test set (5%)

In [542]:
y_predict_test5sk = rbf_svc.predict(X_test5)
confusion_matrix_test5sk = confusion_matrix(y_test5, y_predict_test5sk)
accuracy_score_test5sk = accuracy_score(y_test5, y_predict_test5sk)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test5sk))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test5sk))

Confusion_Matrix:
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score: 0.8154761904761905



In [543]:
diagonals_test5sk = confusion_matrix_test5sk.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test5sk))

Number of Rows Prediction Correctly: 137



In [544]:
precision_test5sk = precision_score(y_test5, y_predict_test5sk, average = "weighted")
precision_test5sk 

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6650014172335601

In [545]:
recall_test5sk = recall_score(y_test5, y_predict_test5sk, average = "weighted")
recall_test5sk 

0.8154761904761905

## SMOTE Resample 5% 

In [546]:
rbf_svc.fit(X_train_oversampled5, y_train_oversampled5)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

### [SMOTE] Predicting on train set (5%)

In [547]:
y_predict_train5sm = rbf_svc.predict(X_train_oversampled5)
confusion_matrix_train5sm = confusion_matrix(y_train_oversampled5, y_predict_train5sm)
accuracy_score_train5sm = accuracy_score(y_train_oversampled5, y_predict_train5sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train5sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train5sm))

Confusion_Matrix:
[[1393   22   21]
 [  84 1254   98]
 [   3   17 1416]]
Accuracy_Score: 0.9431290622098422



In [548]:
skdiagonals_train5sm = confusion_matrix_train5sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(skdiagonals_train5sm))

Number of Rows Prediction Correctly: 4063



In [549]:
precision_train5sm = precision_score(y_train_oversampled5, y_predict_train5sm, average = "weighted")
precision_train5sm

0.9445097910852499

In [550]:
recall_train5sm = recall_score(y_train_oversampled5, y_predict_train5sm, average = "weighted")
recall_train5sm

0.9431290622098422

### [SMOTE] Predicting on test set (5%)

In [551]:
y_predict_test5sm = rbf_svc.predict(X_test5)
confusion_matrix_test5sm = confusion_matrix(y_test5, y_predict_test5sm)
accuracy_score_test5sm = accuracy_score(y_test5, y_predict_test5sm)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test5sm))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test5sm))

Confusion_Matrix:
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score: 0.8154761904761905



In [552]:
diagonals_test5sm = confusion_matrix_test5sm.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test5sm))

Number of Rows Prediction Correctly: 137



In [553]:
precision_test5sm = precision_score(y_test5, y_predict_test5sm, average = "weighted")
precision_test5sm

C:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6650014172335601

In [554]:
recall_test5sm= recall_score(y_test5, y_predict_test5sm, average = "weighted")
recall_test5sm

0.8154761904761905

In [555]:
dfrbf = pd.DataFrame({
    'model': ['RBF SVC 3%', 'RBF SVC 3% SK Resample', 'RBF SVC 3% SMOTE', 'RBF SVC 5%', 'RBF SVC 5% SK Resample', 'RBF SVC 5% SMOTE',],
    'accuracy': [accuracy_score_test3,accuracy_score_test3sk, accuracy_score_test3sm, accuracy_score_test5,accuracy_score_test5sk, accuracy_score_test5sm],
    'recall': [recall_test3, recall_test3sk, recall_test3sm, recall_test5, recall_test5sk, recall_test5sm],
    'precision': [precision_test3, precision_test3sk, precision_test3sm, precision_test5, precision_test5sk, precision_test5sm],
})

dfrbf

model  accuracy    recall  precision
0              RBF SVC 3%  0.511905  0.511905   0.262046
1  RBF SVC 3% SK Resample  0.494048  0.494048   0.471694
2        RBF SVC 3% SMOTE  0.482143  0.482143   0.405945
3              RBF SVC 5%  0.815476  0.815476   0.665001
4  RBF SVC 5% SK Resample  0.815476  0.815476   0.665001
5        RBF SVC 5% SMOTE  0.815476  0.815476   0.665001

In [556]:
results = pd.concat([dflinear, dfrbf], axis = 0)
results

model  accuracy    recall  precision
0              Linear SVC 3%  0.511905  0.511905   0.262046
1  Linear SVC 3% SK Resample  0.345238  0.345238   0.393701
2        Linear SVC 3% SMOTE  0.345238  0.345238   0.394170
3              Linear SVC 5%  0.815476  0.815476   0.665001
4  Linear SVC 5% SK Resample  0.803571  0.803571   0.697554
5        Linear SVC 5% SMOTE  0.738095  0.738095   0.715695
0                 RBF SVC 3%  0.511905  0.511905   0.262046
1     RBF SVC 3% SK Resample  0.494048  0.494048   0.471694
2           RBF SVC 3% SMOTE  0.482143  0.482143   0.405945
3                 RBF SVC 5%  0.815476  0.815476   0.665001
4     RBF SVC 5% SK Resample  0.815476  0.815476   0.665001
5           RBF SVC 5% SMOTE  0.815476  0.815476   0.665001

## Optimizing gamma and c 

In [557]:
C_range = np.logspace(-2, 10, 13)
gamma_range = np.logspace(-9, 3, 13)

params = {'gamma': gamma_range, 'C' : C_range}
rs = RandomizedSearchCV(rbf_svc, params , n_iter = 10, cv = 9)
rs.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [ ]:
rs.best_params_

In [ ]:
rs.best_score_