In [1]:
import pandas as pd 
import numpy as np

In [2]:
X_train = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_train.xlsx")
y_train = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_train.xlsx")

X_test = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\x_test.xlsx")
y_test = pd.read_excel(r"C:\Users\chloe\Desktop\Y4S1\BT4222 DATA MINING\GROUP PROJECT\y_test.xlsx")

In [3]:
X_train = X_train.iloc[: , 1:]
y_train = y_train.iloc[: , 1:]

X_test = X_test.iloc[: , 1:]
y_test = y_test.iloc[: , 1:]

In [4]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1511, 11), (168, 11), (1511, 1), (168, 1))

In [30]:
import sklearn
assert sklearn.__version__ >= "0.20"

from sklearn.svm import SVC
from sklearn import svm
from sklearn.svm import LinearSVC 
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

 # Linear SVM


In [6]:
linearsvc = LinearSVC(C=1, loss="hinge", random_state=42)
linearsvc.fit(X_train, y_train)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(C=1, loss='hinge', random_state=42)

## Predicting on train set


In [7]:
y_predict_train = linearsvc.predict(X_train)
confusion_matrix_train = confusion_matrix(y_train, y_predict_train)
accuracy_score_train = accuracy_score(y_train, y_predict_train)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train))

Confusion_Matrix:
[[   0   30    0]
 [   0 1436    0]
 [   0   45    0]]
Accuracy_Score: 0.9503639973527466



In [8]:
diagonals_train = confusion_matrix_train.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_train))

Number of Rows Prediction Correctly: 1436



In [9]:
TP_train = confusion_matrix_train[1, 1]
TN_train = confusion_matrix_train[0, 0]
FP_train = confusion_matrix_train[0, 1]
FN_train = confusion_matrix_train[1, 0]

In [10]:
precision_train = print(FP_train / (TN_train + FP_train))
precision_train 

1.0


In [11]:
recall_train = print(TP_train / (TP_train + FN_train))
recall_train 

1.0


## Predicting on test set

In [12]:
y_predict_test = linearsvc.predict(X_test)
confusion_matrix_test = confusion_matrix(y_test, y_predict_test)
accuracy_score_test = accuracy_score(y_test, y_predict_test)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test))

Confusion_Matrix:
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score: 0.8154761904761905



In [13]:
diagonals_test = confusion_matrix_test.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test))

Number of Rows Prediction Correctly: 137



In [14]:
TP_test = confusion_matrix_test[1, 1]
TN_test = confusion_matrix_test[0, 0]
FP_test = confusion_matrix_test[0, 1]
FN_test = confusion_matrix_test[1, 0]

In [15]:
precision_test = print(FP_test / (TN_test + FP_test))
precision_test 

1.0


In [16]:
recall_test = print(TP_test / (TP_test + FN_test))
recall_test 

1.0


## Optimizing C

In [53]:
C_range = np.logspace(-2, 10, 13)

params = {'C' : C_range}
rs = RandomizedSearchCV(linearsvc, params , n_iter = 10, cv = 9)
rs.fit(X_train, y_train)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y t

C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\s

C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\s

C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\s

C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Python39\lib\s

RandomizedSearchCV(cv=9,
                   estimator=LinearSVC(C=1, loss='hinge', random_state=42),
                   param_distributions={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05,
       1.e+06, 1.e+07, 1.e+08, 1.e+09, 1.e+10])})

In [54]:
rs.best_params_

{'C': 100000000.0}

In [55]:
rs.best_score_

0.9503651427304123

### Running with optimized C
No Difference from non-optimized C

In [56]:
linearsvc_trained = LinearSVC(C=100000000.0, loss="hinge", random_state=42)
linearsvc_trained.fit(X_train, y_train)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(C=100000000.0, loss='hinge', random_state=42)

#### Predicting on train set


In [57]:
y_predict_train_train = linearsvc_trained.predict(X_train)
confusion_matrix_train_train = confusion_matrix(y_train, y_predict_train_train)
accuracy_score_train_train = accuracy_score(y_train, y_predict_train_train)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train_train))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train_train))

Confusion_Matrix:
[[   0   30    0]
 [   0 1436    0]
 [   0   45    0]]
Accuracy_Score: 0.9503639973527466



In [58]:
diagonals_train_train = confusion_matrix_train_train.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_train_train))

Number of Rows Prediction Correctly: 1436



In [59]:
TP_train_train = confusion_matrix_train_train[1, 1]
TN_train_train = confusion_matrix_train_train[0, 0]
FP_train_train = confusion_matrix_train_train[0, 1]
FN_train_train = confusion_matrix_train_train[1, 0]

In [60]:
precision_train_train = print(FP_train_train / (TN_train_train + FP_train_train))
precision_train_train 

1.0


In [61]:
recall_train_train = print(TP_train_train / (TP_train_train + FN_train_train))
recall_train_train

1.0


#### Predicting on test set

In [67]:
y_predict_test_train = linearsvc_trained.predict(X_test)
confusion_matrix_test_train = confusion_matrix(y_test, y_predict_test_train)
accuracy_score_test_train = accuracy_score(y_test, y_predict_test_train)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test_train))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test_train))

Confusion_Matrix:
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score: 0.8154761904761905



In [68]:
diagonals_test_train = confusion_matrix_test_train.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test_train))

Number of Rows Prediction Correctly: 137



In [69]:
TP_test_train = confusion_matrix_test_train[1, 1]
TN_test_train = confusion_matrix_test_train[0, 0]
FP_test_train = confusion_matrix_test_train[0, 1]
FN_test_train = confusion_matrix_test_train[1, 0]

In [70]:
precision_test_train = print(FP_test_train / (TN_test_train + FP_test_train))
precision_test_train 

1.0


In [71]:
recall_test_train = print(TP_test_train / (TP_test_train + FN_test_train))
recall_test_train 

1.0


# RBF SVM

In [17]:
rbf_svc = svm.SVC(kernel='rbf', gamma = "scale")
rbf_svc.fit(X_train, y_train)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

## Predicting on train set

In [18]:
y_predict_train_rbf = rbf_svc.predict(X_train)
confusion_matrix_train_rbf = confusion_matrix(y_train, y_predict_train_rbf)
accuracy_score_train_rbf = accuracy_score(y_train, y_predict_train_rbf)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train_rbf))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train_rbf))

Confusion_Matrix:
[[   0   30    0]
 [   0 1436    0]
 [   0   45    0]]
Accuracy_Score: 0.9503639973527466



In [19]:
diagonals_train_rbf = confusion_matrix_train_rbf.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_train_rbf))

Number of Rows Prediction Correctly: 1436



In [20]:
TP_train_rbf = confusion_matrix_train_rbf[1, 1]
TN_train_rbf = confusion_matrix_train_rbf[0, 0]
FP_train_rbf = confusion_matrix_train_rbf[0, 1]
FN_train_rbf = confusion_matrix_train_rbf[1, 0]

In [21]:
precision_train_rbf = print(FP_train_rbf / (TN_train_rbf + FP_train_rbf))
precision_train_rbf 

1.0


In [22]:
recall_train_rbf = print(TP_train_rbf / (TP_train_rbf + FN_train_rbf))
recall_train_rbf 

1.0


## Predicting on test set

In [23]:
y_predict_test_rbf = linearsvc.predict(X_test)
confusion_matrix_test_rbf = confusion_matrix(y_test, y_predict_test_rbf)
accuracy_score_test_rbf = accuracy_score(y_test, y_predict_test_rbf)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test_rbf))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test_rbf))

Confusion_Matrix:
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score: 0.8154761904761905



In [24]:
diagonals_test_rbf = confusion_matrix_test_rbf.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test_rbf))

Number of Rows Prediction Correctly: 137



In [25]:
TP_test_rbf = confusion_matrix_test_rbf[1, 1]
TN_test_rbf = confusion_matrix_test_rbf[0, 0]
FP_test_rbf = confusion_matrix_test_rbf[0, 1]
FN_test_rbf = confusion_matrix_test_rbf[1, 0]

In [26]:
precision_test_rbf = print(FP_test_rbf / (TN_test_rbf + FP_test_rbf))
precision_test_rbf 

1.0


In [27]:
recall_test_rbf = print(TP_test_rbf / (TP_test_rbf + FN_test_rbf))
recall_test_rbf 

1.0


## Optimizing gamma and c 

In [32]:
C_range = np.logspace(-2, 10, 13)
gamma_range = np.logspace(-9, 3, 13)

params = {'gamma': gamma_range, 'C' : C_range}
rs = RandomizedSearchCV(rbf_svc, params , n_iter = 10, cv = 9)
rs.fit(X_train, y_train)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y,

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y,

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y,

RandomizedSearchCV(cv=9, estimator=SVC(),
                   param_distributions={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05,
       1.e+06, 1.e+07, 1.e+08, 1.e+09, 1.e+10]),
                                        'gamma': array([1.e-09, 1.e-08, 1.e-07, 1.e-06, 1.e-05, 1.e-04, 1.e-03, 1.e-02,
       1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])})

In [33]:
rs.best_params_

{'gamma': 1000.0, 'C': 10000000000.0}

In [34]:
rs.best_score_

0.9503651427304123

### Running with optimized parameters

In [36]:
rbf_svc_trained = svm.SVC(kernel='rbf', gamma = 1000.0, C = 10000000000.0)
rbf_svc_trained.fit(X_train, y_train)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=10000000000.0, gamma=1000.0)

#### Predicting on train set

In [42]:
y_predict_train_rbf_train = rbf_svc_trained.predict(X_train)
confusion_matrix_train_rbf_train = confusion_matrix(y_train, y_predict_train_rbf_train)
accuracy_score_train_rbf_train = accuracy_score(y_train, y_predict_train_rbf_train)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_train_rbf_train))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_train_rbf_train))

Confusion_Matrix:
[[  30    0    0]
 [   0 1436    0]
 [   0    0   45]]
Accuracy_Score: 1.0



In [43]:
diagonals_train_rbf_train = confusion_matrix_train_rbf_train.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_train_rbf_train))

Number of Rows Prediction Correctly: 1511



In [44]:
TP_train_rbf_train = confusion_matrix_train_rbf_train[1, 1]
TN_train_rbf_train = confusion_matrix_train_rbf_train[0, 0]
FP_train_rbf_train = confusion_matrix_train_rbf_train[0, 1]
FN_train_rbf_train = confusion_matrix_train_rbf_train[1, 0]

In [45]:
precision_train_rbf_train = print(FP_train_rbf_train / (TN_train_rbf_train + FP_train_rbf_train))
precision_train_rbf_train 

0.0


In [46]:
recall_train_rbf_train = print(TP_train_rbf_train / (TP_train_rbf_train + FN_train_rbf_train))
recall_train_rbf_train 

1.0


#### Predicting on test set 
No Difference from non-optimized parameters

In [47]:
y_predict_test_rbf_train = rbf_svc_trained.predict(X_test)
confusion_matrix_test_rbf_train = confusion_matrix(y_test, y_predict_test_rbf_train)
accuracy_score_test_rbf_train = accuracy_score(y_test, y_predict_test_rbf_train)
print("Confusion_Matrix:\n{}"
      .format(confusion_matrix_test_rbf_train))
print("Accuracy_Score: {}\n"
      .format(accuracy_score_test_rbf_train))

Confusion_Matrix:
[[  0  10   0]
 [  0 137   0]
 [  0  21   0]]
Accuracy_Score: 0.8154761904761905



In [48]:
diagonals_test_rbf_train = confusion_matrix_test_rbf_train.diagonal().sum()
print("Number of Rows Prediction Correctly: {}\n"
      .format(diagonals_test_rbf_train))

Number of Rows Prediction Correctly: 137



In [49]:
TP_test_rbf_train = confusion_matrix_test_rbf_train[1, 1]
TN_test_rbf_train = confusion_matrix_test_rbf_train[0, 0]
FP_test_rbf_train = confusion_matrix_test_rbf_train[0, 1]
FN_test_rbf_train = confusion_matrix_test_rbf_train[1, 0]

In [50]:
precision_test_rbf_train = print(FP_test_rbf_train / (TN_test_rbf_train + FP_test_rbf_train))
precision_test_rbf_train 

1.0


In [51]:
recall_test_rbf_train = print(TP_test_rbf_train / (TP_test_rbf + FN_test_rbf_train))
recall_test_rbf_train 

1.0
